// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zHotelStatus = z.enum([
    'active',
    'maintenance',
    'closed'
]);

export const zHotelUpsert = z.object({
    name: z.string().min(1),
    location: z.string(),
    status: zHotelStatus
});

export const zHotel = zHotelUpsert.and(z.object({
    id: z.uuid(),
    createdAt: z.iso.datetime()
}));

export const zBookingStatus = z.enum([
    'pending',
    'confirmed',
    'cancelled'
]);

export const zBookingUpsert = z.object({
    hotelId: z.uuid(),
    checkInDate: z.iso.date(),
    checkOutDate: z.iso.date(),
    status: zBookingStatus
});

export const zBooking = zBookingUpsert.and(z.object({
    id: z.uuid(),
    bookingNumber: z.string(),
    createdAt: z.iso.datetime()
}));

export const zLoginRequest = z.object({
    email: z.email(),
    password: z.string().min(1)
});

export const zLoginResponse = z.object({
    accessToken: z.string(),
    user: z.object({
        id: z.uuid(),
        email: z.email()
    })
});

export const zPaginatedResponse = z.object({
    totalItems: z.int(),
    totalPages: z.int(),
    currentPage: z.int(),
    pageSize: z.int()
});

export const zBookingList = zPaginatedResponse.and(z.object({
    items: z.array(zBooking)
}));

export const zError = z.object({
    code: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    message: z.string()
});

export const zValidationError = z.object({
    errors: z.record(z.string(), z.string())
});

export const zGetHotelsQuery = z.object({
    page: z.int().gte(1),
    pageSize: z.int().gte(1),
    status: zHotelStatus.optional()
});

/**
 * A paginated list of hotels
 */
export const zGetHotelsResponse = zPaginatedResponse.and(z.object({
    items: z.array(zHotel)
}));

export const zCreateHotelBody = zHotelUpsert;

/**
 * Hotel created
 */
export const zCreateHotelResponse = zHotel;

export const zDeleteHotelPath = z.object({
    id: z.uuid()
});

/**
 * Hotel deleted
 */
export const zDeleteHotelResponse = z.void();

export const zGetHotelByIdPath = z.object({
    id: z.uuid()
});

/**
 * Hotel details
 */
export const zGetHotelByIdResponse = zHotel;

export const zUpdateHotelBody = zHotelUpsert;

export const zUpdateHotelPath = z.object({
    id: z.uuid()
});

/**
 * Hotel updated
 */
export const zUpdateHotelResponse = zHotel;

export const zGetBookingsQuery = z.object({
    page: z.int().gte(1),
    pageSize: z.int().gte(1)
});

/**
 * A paginated list of bookings
 */
export const zGetBookingsResponse = zBookingList;

export const zCreateBookingBody = zBookingUpsert;

/**
 * Booking created
 */
export const zCreateBookingResponse = zBooking;

export const zDeleteBookingPath = z.object({
    id: z.uuid()
});

/**
 * Booking deleted
 */
export const zDeleteBookingResponse = z.void();

export const zGetBookingByIdPath = z.object({
    id: z.uuid()
});

/**
 * Booking details
 */
export const zGetBookingByIdResponse = zBooking;

export const zUpdateBookingBody = zBookingUpsert;

export const zUpdateBookingPath = z.object({
    id: z.uuid()
});

/**
 * Booking updated
 */
export const zUpdateBookingResponse = zBooking;

export const zLoginBody = zLoginRequest;

/**
 * User authenticated
 */
export const zLoginResponse2 = zLoginResponse;
